exec:
  max_threads: 2
  min_output_tasks: 1
in:
  type: file
  path_prefix: /home/infoobjects/Downloads/sample/calendarFloat.csv
  parser:
    type: csv
    columns:
      - { name: dim_calendar_key, type: long }
      - { name: year_number, type: long }
      - { name: quarter_number, type: long }
      - { name: attr_1, type: string }
filters:
  - type: mssql_lookup
    host: infoobjects-ThinkPad-E490
    database: test
    tablename: countryNew
    username: SA
    password: Mssqlroot95
    mapping_from:
      - quarter_number
      - attr_1
    mapping_to:
      - id
      - country_code
    new_columns:
      - { name: country_name, type: string }
  - type: mssql_lookup
    host: infoobjects-ThinkPad-E490
    database: test
    tablename: countryNew
    username: SA
    password: Mssqlroot95
    mapping_from:
      - quarter_number
      - attr_1
    mapping_to:
      - id
      - country_code
    new_columns:
      - { name: country_address, type: string }
  - type: mssql_lookup
    host: infoobjects-ThinkPad-E490
    database: test
    tablename: countryNew
    username: SA
    password: Mssqlroot95
    mapping_from:
      - quarter_number
      - attr_1
    mapping_to:
      - id
      - country_code
    new_columns:
      - { name: country_code,type: double}
out:
  type: file
  path_prefix: /home/infoobjects/sqlOutput/output.csv
  file_ext: csv
  formatter:
      type: csv
      delimiter: "\t"
      newline: CRLF
      newline_in_field: LF
      charset: UTF-8
      quote_policy: MINIMAL
      quote: '"'
      escape: "\\"
      null_string: "\\N"
      default_timezone: 'UTC'