exec:
  max_threads: 1
  min_output_tasks: 1
in:
  type: file
  path_prefix: /home/infoobjects/Downloads/sample/calendarFloat1 (copy).csv
  parser:
    type: csv
    columns:
      - { name: Country_Name, type: string }
      - { name: quarter_number, type: long }

filters:
  - type: mssql_lookup
    driver_path: /home/infoobjects/Downloads/sqljdbc_1s1.2.0.0_enu/sqljdbc_11.2/enu/mssql-jdbc-11.2.0.jre8.jar
    driver_class: com.microsoft.sqlserver.jdbc.SQLServerDriver
    host: infoobjects-ThinkPad-E490
    database: test
    schemaName: testSchema1
    table_name: cnew
    username: SA
    password: Mssqlroot95
    mapping_from:
      - quarter_number
    mapping_to:
      - qtr_no
    new_columns:
      - { name: qtr_name, type: string }

out:
  type: file
  path_prefix: /home/infoobjects/sqlOutput/output.csv
  file_ext: csv
  formatter:
      type: csv
      delimiter: "\t"
      newline: CRLF
      newline_in_field: LF
      charset: UTF-8
      quote_policy: MINIMAL
      quote: '"'
      escape: "\\"
      null_string: "\\N"
      default_timezone: 'UTC'